include:
  # Elsschot template
  - component: "$CI_SERVER_FQDN/to-be-continuous/custom/elsschot/gitlab-ci-elsschot@1.3"
    inputs:
      prod-enabled: true
      prod-app-name: "db-backup"
  - component: "$CI_SERVER_FQDN/to-be-continuous/docker/gitlab-ci-docker@8.0"
    inputs:
      hadolint-disabled: true
      healthcheck-disabled: true
      trivy-disabled: true
      sbom-disabled: true
      prod-publish-strategy: auto
      snapshot-image: $CI_REGISTRY_IMAGE/snapshot:$CI_COMMIT_REF_SLUG
      release-image: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
